from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', views.login, name='login'),
    path('update-password/', views.update_password, name='update_password'),
    path('leam_lead_show/<int:id>/<str:tag>/', views.teamleader_perticular_leads, name='leam_lead_show'),
    path('export_leads_status_wise_staff/', views.export_leads_status_wise_staff, name='export_leads_status_wise_staff'),
    # path('', views.super_dashboard, name='super_dashboard'),
    path('super_admin/', views.super_admin, name='super_admin'),
    path('super_user_dashboard/', views.super_user_dashboard, name='super_user_dashboard'),
    path('admin_side_leads_record/<str:tag>/', views.admin_side_leads_record, name='admin_side_leads_record'),
    path('admin_add/', views.admin_add, name='admin_add'),
    path('team_dashboard/', views.team_dashboard, name='team_dashboard'),
    path('add_team_leader_user/', views.add_team_leader_user, name='add_team_leader_user'),
    path('team_leader_userss/', views.team_leader_user, name='team_leader_user'),
    # path('home/', views.home, name='home'),
    path('leads/', views.leads, name='leads'),
    path('export_leads_staff/', views.export_leads_staff, name='export_leads_staff'),
    path('customer_details/<str:email>/', views.customer_details, name='customer_details'),
    path('assigned/<str:email>/',views.assigned,name='assigned'),
    
    path('view_profile/', views.view_profile, name='view_profile'),
    # path('add_user/', views.add_user, name='add_user'),
    path('lost_leads/<str:tag>/', views.lost_leads, name='lost_leads'),
    path('import_leads/', views.import_leads, name='import_leads'),
    path('customer/', views.customer, name='customer'),
    path('visits_staff/', views.visits_staff, name='visits_staff'),
    path('maybe/', views.maybe, name='maybe'),
    path('not_picked/', views.not_picked, name='not_picked'),
    path('lost/', views.lost, name='lost'),
    path('total_leads_admin/', views.total_leads_admin, name='total_leads_admin'),
    path('visit_lead_staff_side/', views.visit_lead_staff_side, name='visit_lead_staff_side'),
    # path('staff/', views.staff, name='staff'),
    # path('new_staff_add/', views.new_staff_add, name='new_staff_add'),
    path('logout/', views.logout_view, name='logout'),
    path('status_update/', views.status_update, name='status_update'),
    path('staff_user/', views.staff_user, name='staff_user'),
    path('all_leads_data/<str:tag>/', views.all_leads_data, name='all_leads_data'),
    path('add_staff/', views.add_staff, name='add_staff'),
    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('admin_view_profile/', views.admin_view_profile,name='admin_view_profile'),
    # path('import/', views.import_data, name='import_data'),
    path('excel_upload/', views.excel_upload, name='excel_upload'),
    # path('update_user/', views.update_user, name='update_user'),
    # path('Staff_excel_upload/', views.Staff_excel_upload, name='Staff_excel_upload'),
    path('team_view_profile/', views.team_view_profile, name='team_view_profile'),
    path('staff_view_profile/', views.staff_view_profile, name='staff_view_profile'),
    # path('send-data/', views.send_data, name='send_data'),
    path('adminedit/<int:id>/', views.adminedit, name='editadmin'),
    path('teamedit/<int:id>/', views.teamedit, name='teamedit'),
    path('staffedit/<int:id>/', views.staffedit, name='staffedit'),
    path('bulk_from/', views.bulk_from, name='bulk_from'),
    path('lead/', views.lead, name='lead'),
    path('to-test-data/', views.bulk_from_data, name='bulk_from_data'),
    path('update_send_status/', views.update_send_status, name='update_send_status'),
    path('activitylogs/', views.activitylogs, name='activitylogs'),
    path('log_activity_add/', views.log_activity_add, name='log_activity_add'),
    path('edit-marketing/<str:source>/', views.edit_record, name='edit-marketing'),
    path('update-record/', views.update_record, name='update_record'),
    path('export/', views.export_users, name='export_users'),
    # path('customer_details/<int:id>/',views.customer_details,name='customer_details'),

    path('team_leader_staff_interested_leads/<int:id>/', views.team_leader_staff_interested_leads, name='team_leader_staff_interested_leads'),
    
    path('teamcustomer/<str:tag>/', views.teamcustomer, name='teamcustomer'),
    path('teamlost_leads/', views.teamlost_leads, name='teamlost_leads'),
    path('teammaybe/', views.teammaybe, name='teammaybe'),
    path('teamnot_picked/', views.teamnot_picked, name='teamnot_picked'),
    path('teamlost/', views.teamlost, name='teamlost'),
    path('visit_team_leader_side/', views.visit_team_leader_side, name='visit_team_leader_side'),

    path('lead_user/<int:id>/', views.get_lead_user_data, name='get_lead_user_data'),
    path('lead_user/update/<int:id>/', views.update_lead_user, name='update_lead_user'),
    path('auto-assign/', views.auto_assign_leads, name='auto_assign'),

    path('project/', views.project, name='project'),

    path('send_file/<int:file_id>/', views.send_file_to_client,
        name='send_file_to_client'),
        
    path('executive-manager/add-inquiry/', views.add_inquiry, name="add_inquiry" ),
    path('update-inquiry-forms/<int:id>/', views.update_inquiry_forms, name='update-inquiry-forms'),
    path('interested-not-interested-inquiry/', views.interested_not_interested_inquiry, name="interested-not-interested-inquiry" ),
    path('update-inquiry/<int:id>', views.update_inquiry, name="update_inquiry" ),
    path('update-delivery-status/', views.update_inquiry_status, name="update_delivery" ),
    path('inquiry_-lits/<str:status>', views.pending_inquiry_lists, name="inquiry_lists"),
    # ----------------------------- Super Admin ------------------------------
    path('get-team-leaders/', views.get_team_leaders, name='get_team_leaders'),
    path('get_admin/', views.get_admin, name='get_admin'),
    path('get_staff/', views.get_staff, name='get_staff'),

    path('add_team_leader_admin_side/', views.add_team_leader_admin_side, name='add_team_leader_admin_side'),
    path('add_staff_admin_side/', views.add_staff_admin_side, name='add_staff_admin_side'),
    path('get_team_leaders_admin_side/', views.get_team_leaders_admin_side, name='get_team_leaders_admin_side'),
    path('productivity_index/', views.productivity_index, name='productivity_index'),
    path('staff-productivity/', views.staff_productivity_view, name='staff_productivity_view'),
    path('teamleader_productivity_view/', views.teamleader_productivity_view, name='teamleader_productivity_view'),
    path('admin_productivity_view/', views.admin_productivity_view, name='admin_productivity_view'),
    path('freelancer_productivity_view/', views.freelancer_productivity_view, name='freelancer_productivity_view'),
    path('toggle-user-active/', views.toggle_user_active, name='toggle_user_active'),
    path('super_user_side_staff_leads/<str:tag>/', views.super_user_side_staff_leads, name='super_user_side_staff_leads'),

    path('project_list/<str:tag>/', views.project_list, name='project_list'),
    path('project_edit/<int:id>/', views.project_edit, name='project_edit'),
    path('staff/<int:staff_id>/calendar/', views.staff_productivity_calendar_view, name='staff_calendar'),
    path('check-location/', views.check_location, name='check_location'),
    path('check-superuser/', views.check_superuser, name='check_superuser'),
    path('incentive_slap_staff/<int:staff_id>/', views.incentive_slap_staff, name='incentive_slap_staff'),
    path('add_sell_freelancer/<int:id>/', views.add_sell_freelancer, name='add_sell_freelancer'),

    path('add_freelancer/', views.add_freelancer, name='add_freelancer'),
    path('add_freelancer_super_side/', views.add_freelancer_super_side, name='add_freelancer_super_side'),
    path('team_lead_leads_report/<int:id>/<str:tag>/', views.team_lead_leads_report, name='team_lead_leads_report'),
    path('api/get-matching-leads/', views.get_matching_leads, name='get_matching_leads'),
    path('api/today-interested-leads/', views.today_interested_count, name='today_interested_leads'),
    path('attendance_calendar/<int:id>/', views.attendance_calendar, name='attendance_calendar'),
    path('get-task-details/', views.get_task_details, name='get_task_details'),
    path('get_logo/', views.get_logo, name='get_logo'),
    path('it_staff_list/', views.it_staff_super_admin_side, name='it_staff_list'),
    path('add_lead/', views.AddLeadBySelf, name='add_lead_by_self'),
    path('lead_listory/<int:id>/', views.LeadHistory, name='lead_listory'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
